server:
  port: 8082

spring:
  application:
    name: workload-service

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

  jms:
    pub-sub-domain: false

app:
  security:
    jwt-secret: ${JWT_SECRET:mySecretKeyThatIsAtLeast256BitsLongForHS256Algorithm123456}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE